version: '3'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: pwgio-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.23-alpine
    container_name: pwgio-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  database:
    container_name: pwgio-db
    image: mysql:8
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: yesenin
    ports:
      - "3306:3306"